Repository openshift/vmware-vsphere-csi-driver-operator, pull requests merged in 2022-03, with the labels that each got.

#79 Set fsGroupPolicy in CSIDriver
  assets/csidriver.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
Labels: lgtm, approved

#78 Bug 2060213: Fix node check result cache between checks
  pkg/operator/vspherecontroller/checks/check_nodes.go
  pkg/operator/vspherecontroller/vcsim_framework.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
Labels: lgtm, bugzilla/valid-bug, approved, bugzilla/severity-high, staff-eng-approved, backport-risk-assessed

#81 Bug 2059791: [vSphere CSI driver Operator] didn't update 'vsphere_csi_driver_error' metric value when fixed the error manually
  pkg/operator/vspherecontroller/vspherecontroller.go
Labels: lgtm, bugzilla/severity-medium, bugzilla/valid-bug, approved
