Repository openshift/vmware-vsphere-csi-driver-operator, pull requests merged in 2022-09, with the labels that each got.

#94 STOR-794: Block upgrade when vSphere is < 7.0.2
  pkg/operator/vspherecontroller/checks/check_error.go
  pkg/operator/vspherecontroller/checks/check_nodes.go
  pkg/operator/vspherecontroller/checks/check_vcenter.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
Labels: lgtm, qe-approved, px-approved, docs-approved, approved

#106 OCPBUGS-940: Rework "BlockDriverInstall" to "BlockUpgradeDriverInstall"
  pkg/operator/vspherecontroller/checks/check_error.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
Labels: lgtm, qe-approved, bugzilla/valid-bug, approved, jira/valid-bug, jira/severity-important

#108 OCPBUGS-1067: Recreate storageclass in case it was deleted
  pkg/operator/storageclasscontroller/storageclasscontroller.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
Labels: lgtm, qe-approved, bugzilla/valid-bug, approved, jira/valid-bug, jira/severity-moderate
