Repository openshift/vmware-vsphere-csi-driver-operator, pull requests merged in 2022-01, with the labels that each got.

#66 Bug 2039406: Also logout from restclient
  pkg/operator/vclib/connection.go
Labels: lgtm, bugzilla/severity-medium, bugzilla/valid-bug, approved

#65 Bug 2038389: Avoid event spam for same events
  pkg/operator/vspherecontroller/vsphere_environment_checker_test.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
Labels: lgtm, bugzilla/valid-bug, approved, bugzilla/severity-high

#67 Bug 2040880: Mark cluster upgradeable to be unknown when we can't connect to vcenter
  pkg/operator/vspherecontroller/checks/check_error.go
  pkg/operator/vspherecontroller/checks/check_nodes.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
Labels: lgtm, bugzilla/severity-medium, bugzilla/valid-bug, approved

#68 Bug 2040880: Degrade the OCP cluster if driver is found
  pkg/operator/vspherecontroller/checks/check_error.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
Labels: lgtm, bugzilla/severity-medium, bugzilla/valid-bug, approved

#70 Bug 2043651: Fix bug with nextCheck not being changed correctly
  pkg/operator/vspherecontroller/vsphere_environment_checker.go
  pkg/operator/vspherecontroller/vsphere_environment_checker_test.go
Labels: lgtm, bugzilla/severity-medium, bugzilla/valid-bug, approved

#71 Bug 2043130: vmware-vsphere: Add external-snapshotter permissions to patch snapshots
  assets/rbac/snapshotter_role.yaml
Labels: lgtm, bugzilla/severity-medium, bugzilla/valid-bug, approved

#72 Bug 2047779: Never degrade cluster on storage policy syncResult
  pkg/operator/storageclasscontroller/storageclasscontroller.go
Labels: lgtm, bugzilla/severity-medium, bugzilla/valid-bug, approved

#63 readme: minor fixes
  README.md
Labels: lgtm, approved
