Repository openshift/vmware-vsphere-csi-driver-operator, pull requests merged in 2023-11, with the labels that each got.

#187 OCPBUGS-20481: Fix vsphere csi controller pods from getting constantly restarted
  pkg/operator/vspherecontroller/driver_starter.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#189 OCPBUGS-20481: Implement fallback to configmap when Infra object does not have vCenter
  pkg/operator/testlib/testlib.go
  pkg/operator/vspherecontroller/driver_starter.go
  pkg/operator/vspherecontroller/driver_starter_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#191 OCPBUGS-23342: Add dummy Progressing condition on blocked driver install
  pkg/operator/vspherecontroller/checks/check_error.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference
