Repository openshift/vmware-vsphere-csi-driver-operator, pull requests merged in 2023-12, with the labels that each got.

#193 [release-4.14] OCPBUGS-23169: Fix vsphere csi controller pods from getting constantly restarted
  pkg/operator/testlib/testlib.go
  pkg/operator/vspherecontroller/driver_starter.go
  pkg/operator/vspherecontroller/driver_starter_test.go
Labels: lgtm, qe-approved, cherry-pick-approved, approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#198 OCPBUGS-23306: Add annotation to CSI driver Pod preventing eviction from the cluster-autoscaler
  assets/node.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#202 STOR-1688: Chore: add .snyk file to ignore false positives
  .snyk
Labels: lgtm, qe-approved, px-approved, docs-approved, approved, jira/valid-reference
