Repository openshift/vmware-vsphere-csi-driver-operator, pull requests merged in 2023-04, with the labels that each got.

#145 OCPBUGS-11146: Mark cluster un-upgradeable when CSI migration is disabled
  go.mod
  go.sum
  pkg/operator/starter.go
  pkg/operator/testlib/testlib.go
  pkg/operator/vspherecontroller/checks/api_interface.go
  pkg/operator/vspherecontroller/checks/check_error.go
  pkg/operator/vspherecontroller/checks/check_migration_disabled.go
  pkg/operator/vspherecontroller/vsphere_environment_checker.go
  pkg/operator/vspherecontroller/vsphere_environment_checker_test.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml-patch
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.storage.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, qe-approved, cherry-pick-approved, bugzilla/valid-bug, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#148 OCPBUGS-12260: Add backoff for successful storage policy creations
  pkg/operator/starter.go
  pkg/operator/storageclasscontroller/storageclasscontroller.go
  pkg/operator/storageclasscontroller/storageclasscontroller_test.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Labels: lgtm, bugzilla/valid-bug, approved, jira/valid-bug, jira/valid-reference

#146 OCPBUGS-11294: Add CSI migration metric
  pkg/operator/utils/metric.go
  pkg/operator/utils/topology.go
  pkg/operator/utils/topology_test.go
  pkg/operator/vspherecontroller/vspherecontroller.go
Labels: lgtm, cherry-pick-approved, bugzilla/valid-bug, approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference
