Repository openshift/vmware-vsphere-csi-driver-operator, pull requests merged in 2023-01, with the labels that each got.

#127 OCPBUGS-5472: Fix sc creation on resync
  pkg/operator/storageclasscontroller/storageclasscontroller.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
Labels: lgtm, cherry-pick-approved, bugzilla/valid-bug, approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#129 STOR-1078: Add hostPaths necessary for SELinux mounts
  assets/node.yaml
Labels: lgtm, qe-approved, px-approved, docs-approved, approved

#128 OCPBUGS-5507: Fix sc creation if it is deleted
  pkg/operator/storageclasscontroller/storageclasscontroller.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
Labels: lgtm, cherry-pick-approved, bugzilla/valid-bug, approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#131 Bug 2106736: Add multiplePVsSameID capability
  test/e2e/manifest.yaml
Labels: lgtm, bugzilla/severity-medium, bugzilla/valid-bug, approved

#130 OCPBUGS-5790: Allow cluster to be upgraded even if using multiple datacenters
  go.mod
  go.sum
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/operator/testlib/multiple_dc.ini
  pkg/operator/testlib/multiple_vc.ini
  pkg/operator/testlib/simple_config.ini
  pkg/operator/testlib/testlib.go
  pkg/operator/utils/constants.go
  pkg/operator/utils/topology.go
  pkg/operator/vspherecontroller/checks/check_nodes.go
  vendor/gopkg.in/ini.v1/.gitignore
  vendor/gopkg.in/ini.v1/.travis.yml
  vendor/gopkg.in/ini.v1/LICENSE
  vendor/gopkg.in/ini.v1/Makefile
  vendor/gopkg.in/ini.v1/README.md
  vendor/gopkg.in/ini.v1/data_source.go
  vendor/gopkg.in/ini.v1/deprecated.go
  vendor/gopkg.in/ini.v1/error.go
  vendor/gopkg.in/ini.v1/file.go
  vendor/gopkg.in/ini.v1/helper.go
  vendor/gopkg.in/ini.v1/ini.go
  vendor/gopkg.in/ini.v1/key.go
  vendor/gopkg.in/ini.v1/parser.go
  vendor/gopkg.in/ini.v1/section.go
  vendor/gopkg.in/ini.v1/struct.go
  vendor/modules.txt
Labels: lgtm, cherry-pick-approved, bugzilla/valid-bug, approved, backport-risk-assessed, jira/valid-bug

#132 Bug 2106736: Fix multiplePVsSameID value in tests
  test/e2e/manifest.yaml
Labels: lgtm, bugzilla/severity-medium, bugzilla/valid-bug, approved, jira/valid-bug

#126 STOR-947: support disabling default StorageClass via ClusterCSIDriver
  go.mod
  go.sum
  pkg/operator/storageclasscontroller/storageclasscontroller.go
  pkg/operator/storageclasscontroller/storageclasscontroller_test.go
  pkg/operator/testlib/testlib.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  vendor/github.com/openshift/library-go/pkg/crypto/OWNERS
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csicontrollerset/csi_controller_set.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/modules.txt
Labels: lgtm, qe-approved, px-approved, docs-approved, approved

#133 OCPBUGS-5895: Backport multi dc support 410
  go.mod
  go.sum
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/operator/testlib/multiple_dc.ini
  pkg/operator/testlib/multiple_vc.ini
  pkg/operator/testlib/simple_config.ini
  pkg/operator/testlib/testlib.go
  pkg/operator/utils/constants.go
  pkg/operator/utils/topology.go
  pkg/operator/vspherecontroller/checks/check_nodes.go
  vendor/gopkg.in/ini.v1/.gitignore
  vendor/gopkg.in/ini.v1/.travis.yml
  vendor/gopkg.in/ini.v1/LICENSE
  vendor/gopkg.in/ini.v1/Makefile
  vendor/gopkg.in/ini.v1/README.md
  vendor/gopkg.in/ini.v1/data_source.go
  vendor/gopkg.in/ini.v1/deprecated.go
  vendor/gopkg.in/ini.v1/error.go
  vendor/gopkg.in/ini.v1/file.go
  vendor/gopkg.in/ini.v1/helper.go
  vendor/gopkg.in/ini.v1/ini.go
  vendor/gopkg.in/ini.v1/key.go
  vendor/gopkg.in/ini.v1/parser.go
  vendor/gopkg.in/ini.v1/section.go
  vendor/gopkg.in/ini.v1/struct.go
  vendor/modules.txt
Labels: lgtm, cherry-pick-approved, bugzilla/valid-bug, approved, backport-risk-assessed, jira/valid-bug

#137 OCPBUGS-5895: Fix vendored ini package
  go.mod
  go.sum
  vendor/gopkg.in/ini.v1/.travis.yml
  vendor/gopkg.in/ini.v1/Makefile
  vendor/gopkg.in/ini.v1/README.md
  vendor/gopkg.in/ini.v1/codecov.yml
  vendor/gopkg.in/ini.v1/data_source.go
  vendor/gopkg.in/ini.v1/file.go
  vendor/gopkg.in/ini.v1/ini.go
  vendor/gopkg.in/ini.v1/key.go
  vendor/gopkg.in/ini.v1/parser.go
  vendor/gopkg.in/ini.v1/section.go
  vendor/gopkg.in/ini.v1/struct.go
  vendor/modules.txt
Labels: lgtm, cherry-pick-approved, bugzilla/valid-bug, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
