Repository openshift/vmware-vsphere-csi-driver-operator, pull requests merged in 2023-02, with the labels that each got.

#134 STOR-1128: Change the default SC to the CSI one
  assets/storageclass.yaml
  go.mod
  go.sum
  pkg/operator/storageclasscontroller/storageclasscontroller.go
  pkg/operator/storageclasscontroller/storageclasscontroller_test.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csistorageclasscontroller/csi_storageclass_controller.go
  vendor/modules.txt
Labels: lgtm, qe-approved, px-approved, docs-approved, approved, jira/valid-reference

#138 OCPBUGS-5765: Populate migration datastore url
  assets/csi_cloud_config.ini
  pkg/operator/starter.go
  pkg/operator/storageclasscontroller/storageclasscontroller.go
  pkg/operator/storageclasscontroller/vmware.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/operator/testlib/testlib.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
Labels: lgtm, bugzilla/valid-bug, approved, jira/valid-bug, jira/valid-reference

#135 STOR-1145: Add metric for topology
  pkg/operator/utils/metric.go
  pkg/operator/utils/topology.go
  pkg/operator/utils/topology_test.go
  pkg/operator/vspherecontroller/vspherecontroller.go
Labels: lgtm, qe-approved, px-approved, docs-approved, approved, jira/valid-reference

#122 STOR-1120: Add csi idempotency flags
  assets/vsphere_features_config.yaml
Labels: lgtm, qe-approved, px-approved, docs-approved, approved, jira/valid-reference

#140 OCPBUGS-7482: Do not enable topology features if only one failure-domains is defined
  pkg/operator/utils/topology.go
  pkg/operator/utils/topology_test.go
  pkg/operator/vspherecontroller/vspherecontroller.go
Labels: lgtm, bugzilla/valid-bug, approved, jira/valid-bug, jira/valid-reference

#141 OCPBUGS-7899: Bump sidecar timeouts for vsphere
  assets/controller.yaml
Labels: lgtm, bugzilla/valid-bug, approved, jira/valid-bug, jira/valid-reference

#139 OCPBUGS-7426: Fix datastore migration bug in 4.12
  assets/csi_cloud_config.ini
  pkg/operator/starter.go
  pkg/operator/storageclasscontroller/storageclasscontroller.go
  pkg/operator/storageclasscontroller/vmware.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/operator/testlib/testlib.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
Labels: lgtm, qe-approved, cherry-pick-approved, bugzilla/valid-bug, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
