Repository openshift/vmware-vsphere-csi-driver-operator, pull requests merged in 2023-10, with the labels that each got.

#171 OCPBUGS-18131: Block upgrade to 4.13 via admin ack
  pkg/operator/starter.go
  pkg/operator/testlib/testlib.go
  pkg/operator/vspherecontroller/checks/api_interface.go
  pkg/operator/vspherecontroller/checks/check_error.go
  pkg/operator/vspherecontroller/checks/check_error_test.go
  pkg/operator/vspherecontroller/checks/check_nodes.go
  pkg/operator/vspherecontroller/checks/check_patched_vcenter.go
  pkg/operator/vspherecontroller/checks/check_patched_vcenter_test.go
  pkg/operator/vspherecontroller/vcsim_framework.go
  pkg/operator/vspherecontroller/vsphere_environment_checker.go
  pkg/operator/vspherecontroller/vsphere_environment_checker_test.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
Labels: lgtm, qe-approved, cherry-pick-approved, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#178 OCPBUGS-21826: Warn when managment state is set to values other than Managed
  pkg/operator/vspherecontroller/vspherecontroller.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#179 OCPBUGS-22385:disable http/2 server support in webhook
  assets/webhook/deployment.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#165 STOR-1276: Enable support for mounting volumes with SELinux context
  assets/csidriver.yaml
Labels: lgtm, qe-approved, px-approved, docs-approved, approved, jira/valid-reference
