Repository openshift/vmware-vsphere-csi-driver-operator, pull requests merged in 2024-09, with the labels that each got.

#248 OCPBUGS-38274: Remove conditions and controllers
  Makefile
  go.mod
  go.sum
  pkg/operator/storageclasscontroller/storageclasscontroller.go
  pkg/operator/vspherecontroller/operator_removal.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
  test/e2e/operator_removal_test.go
  test/library/client.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/volumesnapshotclass.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehelper/event_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehelper/resource_helpers.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#250 NO-JIRA: Update "Quick start" section of README
  README.md
Labels: lgtm, qe-approved, px-approved, docs-approved, approved, jira/valid-reference

#251 OCPBUGS-41532: Add check for vCenter version
  pkg/cnsmigration/migrator.go
  pkg/operator/utils/version_check.go
  pkg/operator/utils/version_check_test.go
  pkg/operator/vclib/connection.go
  pkg/operator/vspherecontroller/checks/check_nodes.go
  pkg/operator/vspherecontroller/checks/check_vcenter.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#252 NO-JIRA: Add docs for cns volume migration
  docs/cns-migration.md
Labels: lgtm, qe-approved, px-approved, docs-approved, approved, jira/valid-reference

#258 OCPBUGS-38368: Fix the config loading warning
  third_party/cloud-provider-vsphere/pkg/common/config/config.go
  third_party/cloud-provider-vsphere/pkg/common/config/config_yaml.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
