Repository openshift/vmware-vsphere-csi-driver-operator, pull requests merged in 2024-01, with the labels that each got.

#195 OCPBUGS-24716: Enable new features to prevent CSI driver from crash looping (revert OCPBUGS-23970)
  assets/vsphere_features_config.yaml
Labels: lgtm, qe-approved, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#206 STOR-1714: Release leadership on SIGTERM
  pkg/operator/starter.go
Labels: lgtm, qe-approved, px-approved, docs-approved, approved, jira/valid-reference

#215 OCPBUGS-24421: Rerun checks on reconnect
  pkg/operator/vspherecontroller/vsphere_environment_checker.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#213 OCPBUGS-27242: fix or ignore snyk errors for ocp storage repos
  .snyk
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#212 STOR-1578: Revert "Merge pull request #195 from gnufied/revert-192-enable-new-fe…
  assets/vsphere_features_config.yaml
Labels: lgtm, qe-approved, px-approved, docs-approved, approved, jira/valid-reference

#218 OCPBUGS-27159: Mark the operator as Disabled on connection error
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
