Repository openshift/vmware-vsphere-csi-driver-operator, pull requests merged in 2024-08, with the labels that each got.

#241 STOR-1593: Disable toplogy feature explicitly
  pkg/operator/vspherecontroller/driver_starter.go
Labels: lgtm, qe-approved, px-approved, docs-approved, approved, jira/valid-reference

#228 SPLAT-1637: Initial changes for multi vcenter support.
  assets/csi_cloud_config.ini
  assets/csi_cloud_config_vcenters.ini
  assets/rbac/csi_driver_controller_role.yaml
  go.mod
  go.sum
  pkg/cnsmigration/migrator.go
  pkg/operator/starter.go
  pkg/operator/storageclasscontroller/multivcenterstorageclasscontroller.go
  pkg/operator/storageclasscontroller/storageclasscontroller.go
  pkg/operator/storageclasscontroller/storageclasscontroller_test.go
  pkg/operator/storageclasscontroller/vmware.go
  pkg/operator/storageclasscontroller/vmware_test.go
  pkg/operator/testlib/multiple_dc.yaml
  pkg/operator/testlib/multiple_vc.yaml
  pkg/operator/testlib/testlib.go
  pkg/operator/testlib/vcsim_framework.go
  pkg/operator/utils/topology.go
  pkg/operator/vclib/connection.go
  pkg/operator/vspherecontroller/checks/check_nodes.go
  pkg/operator/vspherecontroller/checks/check_vcenter.go
  pkg/operator/vspherecontroller/checks/interface.go
  pkg/operator/vspherecontroller/config.go
  pkg/operator/vspherecontroller/config_test.go
  pkg/operator/vspherecontroller/driver_starter_test.go
  pkg/operator/vspherecontroller/vsphere_environment_checker_test.go
  pkg/operator/vspherecontroller/vspherecontroller.go
  pkg/operator/vspherecontroller/vspherecontroller_test.go
  third_party/cloud-provider-vsphere/pkg/common/config/config.go
  third_party/cloud-provider-vsphere/pkg/common/config/config_ini_legacy.go
  third_party/cloud-provider-vsphere/pkg/common/config/config_yaml.go
  third_party/cloud-provider-vsphere/pkg/common/config/consts_and_errors.go
  third_party/cloud-provider-vsphere/pkg/common/config/types_common.go
  third_party/cloud-provider-vsphere/pkg/common/config/types_ini_legacy.go
  third_party/cloud-provider-vsphere/pkg/common/config/types_yaml.go
  vendor/github.com/imdario/mergo/.deepsource.toml
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/CONTRIBUTING.md
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/SECURITY.md
  vendor/github.com/imdario/mergo/doc.go
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/features/util.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
  vendor/modules.txt
Labels: lgtm, qe-approved, px-approved, docs-approved, approved, jira/valid-reference

#243 OCPBUGS-37772: Disable CSI migration in multi-vCenter cluster
  go.mod
  pkg/operator/driverfeaturescontroller.go
  pkg/operator/driverfeaturescontroller_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#244 STOR-1819: Add manifest with OCP specific test config
  test/e2e/ocp-tests.yaml
Labels: lgtm, qe-approved, px-approved, docs-approved, approved, jira/valid-reference

#245 OCPBUGS-38026: Implement minor quality of life improvements.
  cmd/cns-migration/main.go
  pkg/cnsmigration/migrator.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#246 OCPBUGS-38272: Restart CSI driver controller pod on config change
  pkg/operator/vspherecontroller/driver_starter.go
  pkg/operator/vspherecontroller/vspherecontroller.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference
