Repository openshift/vmware-vsphere-csi-driver-operator, pull requests merged in 2025-02, with the labels that each got.

#289 [release-4.16] OCPBUGS-49862: List only linux nodes
  pkg/operator/testlib/vcsim_framework.go
  pkg/operator/vspherecontroller/checks/api_interface.go
  pkg/operator/vspherecontroller/checks/check_nodes.go
Labels: lgtm, qe-approved, cherry-pick-approved, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#281 OCPBUGS-48103: Update master to main
  README.md
  pkg/operator/vclib/connection.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#286 STOR-2319: Remove code for CNS migration tool
  Dockerfile.openshift
  cmd/cns-migration/main.go
  docs/cns-migration.md
  go.mod
  go.sum
  pkg/cnsmigration/inuse_volume_store.go
  pkg/cnsmigration/logger.go
  pkg/cnsmigration/migrator.go
  vendor/github.com/fatih/color/.travis.yml
  vendor/github.com/fatih/color/Gopkg.lock
  vendor/github.com/fatih/color/Gopkg.toml
  vendor/github.com/fatih/color/LICENSE.md
  vendor/github.com/fatih/color/README.md
  vendor/github.com/fatih/color/color.go
  vendor/github.com/fatih/color/doc.go
  vendor/github.com/mattn/go-colorable/.travis.yml
  vendor/github.com/mattn/go-colorable/LICENSE
  vendor/github.com/mattn/go-colorable/README.md
  vendor/github.com/mattn/go-colorable/colorable_appengine.go
  vendor/github.com/mattn/go-colorable/colorable_others.go
  vendor/github.com/mattn/go-colorable/colorable_windows.go
  vendor/github.com/mattn/go-colorable/noncolorable.go
  vendor/github.com/mattn/go-isatty/.travis.yml
  vendor/github.com/mattn/go-isatty/LICENSE
  vendor/github.com/mattn/go-isatty/README.md
  vendor/github.com/mattn/go-isatty/doc.go
  vendor/github.com/mattn/go-isatty/isatty_android.go
  vendor/github.com/mattn/go-isatty/isatty_bsd.go
  vendor/github.com/mattn/go-isatty/isatty_others.go
  vendor/github.com/mattn/go-isatty/isatty_solaris.go
  vendor/github.com/mattn/go-isatty/isatty_tcgets.go
  vendor/github.com/mattn/go-isatty/isatty_windows.go
  vendor/k8s.io/utils/set/OWNERS
  vendor/k8s.io/utils/set/ordered.go
  vendor/k8s.io/utils/set/set.go
  vendor/k8s.io/utils/set/set_go_1.20.go
  vendor/k8s.io/utils/set/set_go_1.21.go
  vendor/modules.txt
Labels: lgtm, qe-approved, approved, jira/valid-reference, acknowledge-critical-fixes-only

#283 OCPBUGS-43273: fix panic when vcenter address is incorrect
  pkg/operator/vclib/connection.go
  pkg/operator/vspherecontroller/vspherecontroller.go
Labels: lgtm, qe-approved, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
